name: grid_practice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  path: ^1.9.0
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_bounceable: ^1.2.0
  google_maps_flutter: ^2.3.0
  path_provider: ^2.1.1
  geocoding: ^3.0.0
  another_flushbar: ^1.12.30
  shared_preferences: ^2.3.5
  badges: ^3.1.2
  loading_animation_widget: ^1.3.0
  google_nav_bar: ^5.0.7
  add_to_cart_animation: ^2.0.4
  flutter_icon_snackbar: ^1.2.1
  flutter_swipe_button: ^2.1.3
  cached_network_image: ^3.4.1
  intl: ^0.20.1
  geolocator: ^13.0.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/debit/
    - assets/gif/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
